---
# Per environment values which override defaults in hmpps-court-case-data-migration-service/values.yaml

generic-service:
  replicaCount: 1

  ingress:
    host: court-case-data-migration-service-test.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: "test"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.test.json"
    HMPPS_AUTH_URL: "https://sign-in-test.hmpps.service.justice.gov.uk/auth"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-probation-in-court-nonprod
